#! /usr/bin/env bash
set -e
# ---------------------------------------------------------------------
# -- This script is checking whether CRDS are installed or not
# ---------------------------------------------------------------------
ATTEMPTS_AMOUNT="${TEST_ATTEMPTS_AMOUNT:-10}"
ATTEMPTS_TIMEOUT="${TEST_ATTEMPTS_TIMEOUT:-30}"
INSTALLED="${TEST_INSTALLED:-true}"
CRDS=("databases.kinda.rocks" "dbinstances.kinda.rocks" "dbusers.kinda.rocks")
TEST_PASSED=false

for _ in $(seq 1 "${ATTEMPTS_AMOUNT}"); do
  for CRD in "${CRDS[@]}"; do
    SUCCESS=true
    if ! kubectl get crd "$CRD"; then
      SUCCESS=false
    fi;
    if [ "${SUCCESS}" == "${INSTALLED}" ]; then
      echo "[INFO]: Test is passed, ${CRD} installed -> ${INSTALLED}"
      TEST_PASSED=true;
    else
      TEST_PASSED=false
      break
    fi
  done
  if [ "${TEST_PASSED}" == "true" ]; then
    exit 0
  fi
  echo "[INFO]: Sleeping ${ATTEMPTS_TIMEOUT} seconds"
  sleep "$ATTEMPTS_TIMEOUT"
done

echo "[ERROR]: Test is failed, check the kubectl get crds output"
kubectl get crds
exit 1;
