---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "db-operator.name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: "controller"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "controller"
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
        app.kubernetes.io/component: "controller"
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | trim | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/controller/config.yaml") . | sha256sum }}
        {{- if .Values.annotations }}
        {{ toYaml .Values.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "db-operator.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: operator
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ template "github_packages_image_version" . }}"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - db-operator
          {{- if (include "db-operator.args" . ) }}
          args:
            {{- range include "db-operator.args" $ | split "," }}
            - {{ . }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.image.logLevel }}
            - name: OPERATOR_NAME
              value: "db-operator"
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace | quote }}
            - name: RECONCILE_INTERVAL
              value: {{ .Values.reconcileInterval | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            {{- if .Values.secrets.gsql }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/run/secrets/gcloudsqladmin/credentials.json"
            {{- if .Values.secrets.gsql.readonly }}
            - name: GCSQL_CLIENT_CREDENTIALS
              value: "/run/secrets/gcloudsqlclient/credentials.json"
            {{- end }}
            {{- end }}
            - name: CONFIG_PATH
              value: "/run/config/config.yaml"
          volumeMounts:
          {{- if .Values.secrets.gsql }}
          - mountPath: /run/secrets/gcloudsqladmin
            name: serviceaccount-cloudsql-admin
            readOnly: true
          {{- if .Values.secrets.gsql.readonly }}
          - mountPath: /run/secrets/gcloudsqlclient
            name: serviceaccount-cloudsql-client
            readOnly: true
          {{- end }}
          {{- end }}
          - mountPath: /run/config/
            name: config-volume
            readOnly: true
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{ toYaml .Values.affinity  | nindent 8 }}
      tolerations:
        {{ toYaml .Values.tolerations | nindent 8 }}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.secrets.gsql }}
        - name: serviceaccount-cloudsql-admin
          secret:
            defaultMode: 420
            secretName: cloudsql-admin-serviceaccount
      {{- if .Values.secrets.gsql.readonly }}
        - name: serviceaccount-cloudsql-client
          secret:
            defaultMode: 420
            secretName: cloudsql-readonly-serviceaccount
      {{- end }}
      {{- end }}
        - name: config-volume
          configMap: 
            name: {{ template "db-operator.name" . }}-config
